#! /bin/sh

# Autostarts
sxhkd &
picom &
# nitrogen --restore &
greenclip daemon &
udiskie &
betterlockscreen -w
$HOME/.config/polybar/launch.sh

xidlehook \
	`# Don't lock when there's a fullscreen application` \
	--not-when-fullscreen \
	`# Don't lock when there's audio playing` \
	--not-when-audio \
	`# Dim the screen after 60 seconds, undim if user becomes active` \
	--timer 120 \
	'echo $(xbacklight -get) > /tmp/brightness.dat; xbacklight -set 1' \
	'[ -f /tmp/brightness.dat ] && xbacklight -set $(cat /tmp/brightness.dat) || xbacklight -set 50' \
	`# Undim & lock after 10 more seconds` \
	--timer 10 \
	'xset dpms force off; betterlockscreen -l' \
	'[ -f /tmp/brightness.dat ] && xbacklight -set $(cat /tmp/brightness.dat) || xbacklight -set 50' &
	# `# Finally, suspend an hour after it locks` \
	#--timer 3600 \
	#'systemctl suspend' \
	#''

bspc monitor -d ws1 ws2 ws3 ws4 ws5 ws6 ws7 ws8 ws9 ws0

bspc config border_width         4
bspc config window_gap           8

bspc config top_padding         20
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# some disabled
# bspc config single_monocle                false
# bspc config click_to_focus                true
# bspc config focus_by_distance             true
# bspc config focus_follows_pointer         true
# bspc config history_aware_focus           true
# bspc config remove_disabled_monitors      true
# bspc config merge_overlapping_monitors    true


# bspc config pointer_modifier     mod4
# bspc config pointer_action1      move
# bspc config pointer_action2      resize_side
# bspc config pointer_action3      resize_corner

#### BSPWM coloring ####
bspc config normal_border_color	      "#4c566a"
bspc config active_border_color	      "#1e1e1e"
bspc config focused_border_color      "#ff0000"
bspc config presel_feedback_color     "#5e81ac"
bspc config urgent_border_color       "#dd2727"

# This will be used when polybar should always be on top
# with transulent polybars I suppose
#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP1)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_VIRTUAL1)
