#! /bin/sh

# Some variables
gap=15
PANEL_HEIGHT=25

export gap
export PANEL_HEIGHT

# Autostarts are moved to .config/bspwm/autostart

bspc monitor -d ws1 ws2 ws3 ws4 ws5 ws6 ws7 ws8 ws9 ws0
#bspc monitor -d i ii iii iv v vi vii viii ix x
#bspc monitor -d One Two Three Four Five Six Seven Eight Nine Ten
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d • • • • • • • • • •
#bspc monitor -d I II III IV V VI


#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap;
bspc config top_padding $(($PANEL_HEIGHT-$gap))
bspc config left_padding -$gap
bspc config right_padding -$gap
bspc config bottom_padding -$gap

#Various settings
#Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config gapless_monocle		false 
bspc config borderless_monocle		true
bspc config single_monocle		true
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true
## Honor size hints: do not make windows smaller than they wish to be
bspc config honor_size_hints true 
## Some keybindings automatically enable and disable this setting
# bspc config pointer_follows_focus true 
# bspc config merge_overlapping_monitors    true
# bspc config click_to_focus                true
# bspc config focus_by_distance             true
# bspc config history_aware_focus           true

bspc config border_width         4

bspc config split_ratio          0.52

# bspc config pointer_modifier     mod4
# bspc config pointer_action1      move
# bspc config pointer_action2      resize_side
# bspc config pointer_action3      resize_corner

## BSPWM coloring ####
bspc config normal_border_color	      "#4c566a"
bspc config active_border_color	      "#1e1e1e"
bspc config focused_border_color      "#ff0000"
bspc config presel_feedback_color     "#5e81ac"
bspc config urgent_border_color       "#dd2727"

## Automatic gap based on number of windows
autogap &
limepanel &
